name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Upgrade pip
        run: |
          python3 -m pip install --upgrade pip
        
      - name: Install dependencies
        run: |
          python3 -m pip install -r ./requirements.txt
          
      - name: Cache thumbs
        id: cache-thumbs
        uses: actions/cache@v2
        with:
          path: ./output/thumbs
          key: ${{runner.os}}-thumbs
          
      - name: Build the website
        run: make
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
